import type { Metadata } from "next";
import "./globals.css";
import {ThemeProvider as NextThemesProvider} from "next-themes";


export const metadata: Metadata = {
  title: "e-ticaret",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body>
      <NextThemesProvider attribute="class" defaultTheme="dark" enableSystem>
            {children}
          </NextThemesProvider>
      </body>
    </html>
  );
}
